begin;

create table if not exists public.duke_football_games (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date timestamp,
  season integer,
  week integer,
  "teamAScore" smallint,
  "teamBScore" smallint,
  "neutralSite" boolean,
  city text,
  state text,
  notes text,
  forfeited boolean,
  vacated boolean,
  "teamA" json,
  "teamB" json,
  bowl json
);

comment on table public.duke_football_games is 'table to hold all historical game data for duke football games';

create table if not exists public.tweeted_scores (
  id bigint generated by default as identity primary key,
  game_id bigint not null,
  score_key text,
  tweeted_at timestamptz default (now() at time zone 'utc')
);

comment on table public.tweeted_scores is 'helps detemine if tweet should go out or now';

commit;
