begin;

create or replace function public.newsletter_editorial_audit_sections_bounded(p_value jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  entry record;
  reason jsonb;
begin
  if jsonb_typeof(p_value) <> 'object'
    or (select count(*) from jsonb_object_keys(p_value)) > 5
    or octet_length(p_value::text) > 16384 then
    return false;
  end if;
  for entry in select key, value from jsonb_each(p_value) loop
    if char_length(entry.key) > 64
      or jsonb_typeof(entry.value) <> 'object'
      or jsonb_typeof(entry.value->'disposition') <> 'string'
      or char_length(entry.value->>'disposition') > 32
      or jsonb_typeof(entry.value->'rejectionReasons') <> 'array'
      or jsonb_array_length(entry.value->'rejectionReasons') > 16 then
      return false;
    end if;
    for reason in select value from jsonb_array_elements(entry.value->'rejectionReasons') loop
      if jsonb_typeof(reason) <> 'string' or char_length(reason #>> '{}') > 128 then
        return false;
      end if;
    end loop;
  end loop;
  return true;
end;
$$;

create or replace function public.newsletter_editorial_audit_warnings_bounded(p_value jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  warning jsonb;
begin
  if jsonb_typeof(p_value) <> 'array'
    or jsonb_array_length(p_value) > 8
    or octet_length(p_value::text) > 2048 then
    return false;
  end if;
  for warning in select value from jsonb_array_elements(p_value) loop
    if jsonb_typeof(warning) <> 'string' or char_length(warning #>> '{}') > 128 then
      return false;
    end if;
  end loop;
  return true;
end;
$$;

create table if not exists public.newsletter_editorial_audits (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.newsletter_issues(id) on delete cascade,
  delivery_id bigint not null references public.newsletter_deliveries(id) on delete cascade,
  attempt integer not null default 1 check (attempt between 1 and 1000),
  mode text not null check (char_length(mode) between 1 and 64),
  provider text check (provider is null or char_length(provider) between 1 and 64),
  model text check (model is null or char_length(model) between 1 and 128),
  packet_version text not null check (char_length(packet_version) between 1 and 64),
  schema_version text not null check (char_length(schema_version) between 1 and 64),
  validator_version text not null check (char_length(validator_version) between 1 and 64),
  fallback_version text not null check (char_length(fallback_version) between 1 and 64),
  section_results jsonb not null,
  discovery_warnings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.newsletter_editorial_audits
  add column if not exists attempt integer not null default 1;

alter table public.newsletter_editorial_audits
  alter column delivery_id set not null;

alter table public.newsletter_editorial_audits
  drop constraint if exists newsletter_editorial_audits_attempt_check,
  drop constraint if exists newsletter_editorial_audits_section_results_check,
  drop constraint if exists newsletter_editorial_audits_discovery_warnings_check;

alter table public.newsletter_editorial_audits
  add constraint newsletter_editorial_audits_attempt_check check (attempt between 1 and 1000),
  add constraint newsletter_editorial_audits_section_results_check check (public.newsletter_editorial_audit_sections_bounded(section_results)),
  add constraint newsletter_editorial_audits_discovery_warnings_check check (public.newsletter_editorial_audit_warnings_bounded(discovery_warnings));

create unique index if not exists newsletter_deliveries_id_issue_id_key
  on public.newsletter_deliveries(id, issue_id);
create unique index if not exists newsletter_editorial_audits_delivery_attempt_key
  on public.newsletter_editorial_audits(delivery_id, attempt);

alter table public.newsletter_editorial_audits
  drop constraint if exists newsletter_editorial_audits_delivery_id_fkey;

alter table public.newsletter_editorial_audits
  add constraint newsletter_editorial_audits_delivery_issue_fkey
  foreign key (delivery_id, issue_id)
  references public.newsletter_deliveries(id, issue_id);

alter table public.newsletter_editorial_audits enable row level security;

create or replace function public.reject_newsletter_editorial_audit_mutation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception 'newsletter editorial audit rows are append-only';
end;
$$;

create or replace function public.validate_newsletter_editorial_audit_linkage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  delivery_issue_id bigint;
  delivery_attempts integer;
begin
  if new.delivery_id is null then return new; end if;
  select issue_id, attempts into delivery_issue_id, delivery_attempts
  from public.newsletter_deliveries where id = new.delivery_id;
  if delivery_issue_id is null or delivery_issue_id <> new.issue_id then
    raise exception 'newsletter editorial audit delivery does not belong to issue';
  end if;
  if new.attempt <> coalesce(delivery_attempts, 0) then
    raise exception 'newsletter editorial audit attempt does not match delivery attempt';
  end if;
  return new;
end;
$$;

drop trigger if exists newsletter_editorial_audits_validate_linkage on public.newsletter_editorial_audits;
create trigger newsletter_editorial_audits_validate_linkage
before insert on public.newsletter_editorial_audits
for each row execute function public.validate_newsletter_editorial_audit_linkage();

drop trigger if exists newsletter_editorial_audits_no_update on public.newsletter_editorial_audits;
create trigger newsletter_editorial_audits_no_update
before update or delete on public.newsletter_editorial_audits
for each row execute function public.reject_newsletter_editorial_audit_mutation();

revoke all on table public.newsletter_editorial_audits from public, anon, authenticated, service_role;
grant insert on table public.newsletter_editorial_audits to service_role;
grant usage, select on sequence public.newsletter_editorial_audits_id_seq to service_role;
revoke all on function public.reject_newsletter_editorial_audit_mutation() from public, anon, authenticated;
grant execute on function public.reject_newsletter_editorial_audit_mutation() to service_role;
revoke all on function public.validate_newsletter_editorial_audit_linkage() from public, anon, authenticated;
grant execute on function public.validate_newsletter_editorial_audit_linkage() to service_role;
revoke all on function public.newsletter_editorial_audit_sections_bounded(jsonb) from public, anon, authenticated;
revoke all on function public.newsletter_editorial_audit_warnings_bounded(jsonb) from public, anon, authenticated;

commit;
