begin;

create table if not exists public.sports (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  sport_id bigint not null references public.sports(id),
  slug text not null,
  name text not null,
  short_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (sport_id, slug)
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  sport_id bigint not null references public.sports(id),
  canonical_key text not null unique,
  legacy_duke_game_id bigint unique,
  season integer not null,
  week integer,
  start_at timestamptz,
  status text not null default 'scheduled',
  venue_name text,
  city text,
  state text,
  neutral_site boolean,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_participants (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  team_id bigint not null references public.teams(id),
  participant_role text not null check (participant_role in ('home', 'away')),
  score smallint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (game_id, participant_role)
);

create table if not exists public.game_source_records (
  id bigint generated by default as identity primary key,
  game_id bigint references public.games(id) on delete cascade,
  provider text not null,
  external_game_id text not null,
  payload jsonb not null,
  payload_hash text,
  source_updated_at timestamptz,
  fetched_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (provider, external_game_id)
);

create table if not exists public.game_analytics (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  provider text not null,
  metric_set text not null,
  payload jsonb not null,
  fetched_at timestamptz not null default now(),
  unique (game_id, provider, metric_set)
);

create table if not exists public.game_facts (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  fact_key text not null,
  value jsonb not null,
  logic_version text not null,
  computed_at timestamptz not null default now(),
  unique (game_id, fact_key, logic_version)
);

create table if not exists public.editorial_directives (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  issue_type text not null,
  tier smallint not null check (tier between 1 and 3),
  directive_key text not null,
  facts jsonb not null,
  priority integer not null default 0,
  logic_version text not null,
  created_at timestamptz not null default now(),
  unique (game_id, issue_type, directive_key, logic_version)
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  status text not null default 'pending' check (status in ('pending', 'active', 'unsubscribed', 'bounced')),
  first_name text,
  last_name text,
  consent_source text,
  consented_at timestamptz,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists newsletter_subscribers_email_key
  on public.newsletter_subscribers (lower(email));

create table if not exists public.subscriber_preferences (
  subscriber_id bigint not null references public.newsletter_subscribers(id) on delete cascade,
  publication_key text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (subscriber_id, publication_key)
);

create table if not exists public.newsletter_issues (
  id bigint generated by default as identity primary key,
  publication_key text not null,
  issue_date date not null,
  status text not null default 'draft' check (status in ('draft', 'ready', 'sending', 'sent', 'failed')),
  subject text,
  preview_text text,
  directive jsonb,
  html_body text,
  text_body text,
  template_version text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (publication_key, issue_date)
);

create table if not exists public.newsletter_issue_games (
  issue_id bigint not null references public.newsletter_issues(id) on delete cascade,
  game_id bigint not null references public.games(id) on delete cascade,
  section_key text not null,
  position integer not null default 0,
  primary key (issue_id, game_id, section_key)
);

create table if not exists public.newsletter_deliveries (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.newsletter_issues(id) on delete cascade,
  subscriber_id bigint not null references public.newsletter_subscribers(id) on delete cascade,
  provider_message_id text,
  status text not null default 'queued' check (status in ('queued', 'sent', 'delivered', 'bounced', 'failed')),
  sent_at timestamptz,
  opened_at timestamptz,
  clicked_at timestamptz,
  error text,
  unique (issue_id, subscriber_id)
);

insert into public.sports (slug, name)
values ('football', 'College Football')
on conflict (slug) do nothing;

create index if not exists teams_sport_id_idx on public.teams (sport_id);
create index if not exists games_sport_season_idx on public.games (sport_id, season);
create index if not exists games_start_at_idx on public.games (start_at);
create index if not exists game_participants_game_id_idx on public.game_participants (game_id);
create index if not exists game_sources_game_id_idx on public.game_source_records (game_id);
create index if not exists game_analytics_game_id_idx on public.game_analytics (game_id);
create index if not exists game_facts_game_id_idx on public.game_facts (game_id);
create index if not exists editorial_directives_game_id_idx on public.editorial_directives (game_id);
create index if not exists newsletter_issues_date_idx on public.newsletter_issues (issue_date);
create index if not exists newsletter_deliveries_status_idx on public.newsletter_deliveries (status);

alter table public.sports enable row level security;
alter table public.teams enable row level security;
alter table public.games enable row level security;
alter table public.game_participants enable row level security;
alter table public.game_source_records enable row level security;
alter table public.game_analytics enable row level security;
alter table public.game_facts enable row level security;
alter table public.editorial_directives enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.subscriber_preferences enable row level security;
alter table public.newsletter_issues enable row level security;
alter table public.newsletter_issue_games enable row level security;
alter table public.newsletter_deliveries enable row level security;

commit;
