begin;

create table if not exists public.media_guide_editions (
  id bigint generated by default as identity primary key,
  edition_year integer not null unique,
  title text not null,
  source_file text not null,
  page_count integer,
  source_sha256 text,
  reviewed_at date,
  imported_at timestamptz not null default now()
);

create table if not exists public.media_guide_claims (
  id bigint generated by default as identity primary key,
  edition_id bigint not null references public.media_guide_editions(id) on delete cascade,
  claim_key text not null,
  category text not null,
  payload jsonb not null,
  page_start integer not null,
  page_end integer,
  source_label text,
  verification_status text not null default 'verified',
  created_at timestamptz not null default now(),
  unique (edition_id, claim_key)
);

create index if not exists media_guide_claims_edition_category_idx
  on public.media_guide_claims (edition_id, category);

alter table public.media_guide_editions enable row level security;
alter table public.media_guide_claims enable row level security;

commit;
